version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app  # Mount local code into the container
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
